service: telegram-service

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  dotenv:
    basePath: ../

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  api:
    handler: src/handler.handleApiGatewayRequest
    events:
      - http:
          path: /
          method: any
          cors: true
