AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60

Resources:
  TelegramServiceFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .
      Handler: de.nak.home_assistant.Handler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: 
        Variables:
          DB_URL: "http://host.docker.internal:8080/"
          DB_TOKEN: ""
          BOT_TOKEN: ""
          BOT_USERNAME: "wp_home_assistant_bot"
      Events:
        WebhookApi:
          Type: Api 
          Properties:
            Path: /api
            Method: any
