AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20

Resources:
  TelegramServiceFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .
      Handler: de.nak.home_assistant.Handler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: 
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /api
            Method: get
