service: fritz-service
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true
    packager: "npm"

provider:
  apiGateway:
    shouldStartNameWithService: true
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  api:
    handler: src/handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
