service: hue-service
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    includeModules: true
    packager: "npm"
  dotenv:
    basePath: ../

provider:
  apiGateway:
    shouldStartNameWithService: true
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  callback:
    handler: src/callback.handler
    events:
      - http: ANY /callback
  api:
    handler: src/handler.handler
    events:
      - http: ANY /handler
