version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "db-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ptc9lcm3pezt"
s3_prefix = "db-service"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
