AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - db-service

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java8
    Environment:
      Variables:
        AUTH_USER: ""
        AUTH_PASSWORD: ""
        DatasourceUrl: ""
        DatasourceUsername: ""
        DatasourcePassword: ""
        AWS_ACCESS_KEY_ID: ""
        AWS_SECRET_ACCESS_KEY: ""

Resources:
  DBServicePostModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.module.PostModule::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /module
            Method: post

  DBServiceGetModules:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.module.GetModules::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /module
            Method: get

  DBServiceDeleteModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.module.DeleteModule::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /module/{id}
            Method: delete

  DBServicePostUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.PostUser::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: post

  DBServiceGetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.GetUsers::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user
            Method: get

  DBServiceDeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.DeleteUser::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: delete

  DBServicePutUserModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.PutUserModule::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}/module/{moduleId}
            Method: put

  DBServiceDeleteUserModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.DeleteUserModule::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}/module/{moduleId}
            Method: delete

  DBServiceGetUserModules:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.GetUserModules::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}/module
            Method: get

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ModuleTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
