AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - db-service

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Runtime: java8
    Environment:
      Variables:
        AUTH_USER: "Admin"
        AUTH_PASSWORD: ""

Resources:
  DBServicePostModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.module.PostModule::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /module
            Method: post

  DBServiceGetModules:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.module.GetModules::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /module
            Method: get

  DBServiceDeleteModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.module.DeleteModule::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /module/{moduleId}
            Method: delete

  DBServicePostUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.PostUser::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: post

  DBServiceGetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.GetUsers::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user
            Method: get

  DBServiceDeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.DeleteUser::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: delete

  DBServicePutUserModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.PutUserModule::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}/module/{moduleId}
            Method: put

  DBServiceDeleteUserModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.DeleteUserModule::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}/module/{moduleId}
            Method: delete

  DBServiceGetUserModules:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.GetUserModules::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}/module
            Method: get

  DBServiceGetUserModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.user.GetUserModule::handleRequest
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: target/userdb-0.0.1-SNAPSHOT.jar
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /user/{userId}/module/{moduleId}
            Method: get

  ModuleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ModuleTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: N
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
