AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - db-service

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java8
    Environment:
      Variables:
        ServiceUser: ""
        ServicePassword: ""
        DatasourceUrl: ""
        DatasourceUsername: ""
        DatasourcePassword: ""

Resources:
  DBServiceCreateModule:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.nak.telegram_home_assistant.handler.ModuleHandler::handleRequest
      Policies: AWSLambdaBasicExecutionRole
      CodeUri: .
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /module
            Method: post

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ModuleTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
