name: Deploy Serverless

on: 
  workflow_dispatch:
    inputs:
      service:
        description: 'Service Name (folder name)'     
        required: true
        default: ''

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Serverless Framework
      run: npm install -g serverless
    
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

    - name: Decrypt Secrets
      run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PASSPHRASE }}" --output .env.production .env.production.gpg

    - name: Install
      working-directory: ${{ github.event.inputs.service }}
      run: yarn

    - name: Deploy Lambda functions
      working-directory: ${{ github.event.inputs.service }}
      run: sls deploy --env production